rm: cannot remove '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/*': No such file or directory
Executing test in ozone-ha
Removing network ozone-ha_default
Network ozone-ha_default not found.
Creating network "ozone-ha_default" with the default driver
Pulling datanode (apache/ozone-runner:20220623-1)...
20220623-1: Pulling from apache/ozone-runner
Digest: sha256:ba2ed07322bc8f888150fa2a1ec0523fca85e09c8eb9779445f8bca0d58cff97
Status: Downloaded newer image for apache/ozone-runner:20220623-1
Creating ozone-ha_s3g_1 ... 
Creating ozone-ha_scm2_1 ... 
Creating ozone-ha_om2_1  ... 
Creating ozone-ha_scm3_1 ... 
Creating ozone-ha_recon_1 ... 
Creating ozone-ha_om1_1   ... 
Creating ozone-ha_datanode_1 ... 
Creating ozone-ha_datanode_2 ... 
Creating ozone-ha_datanode_3 ... 
Creating ozone-ha_om3_1      ... 
Creating ozone-ha_scm1_1     ... 
Creating ozone-ha_scm1_1     ... done
Creating ozone-ha_datanode_1 ... done
Creating ozone-ha_om3_1      ... done
Creating ozone-ha_om1_1      ... done
Creating ozone-ha_scm3_1     ... done
Creating ozone-ha_datanode_3 ... done
Creating ozone-ha_s3g_1      ... done
Creating ozone-ha_scm2_1     ... done
Creating ozone-ha_datanode_2 ... done
Creating ozone-ha_om2_1      ... done
Creating ozone-ha_recon_1    ... done
SECONDS: 100
com.google.protobuf.ServiceException: java.net.ConnectException: Call From 2a85192916ff/172.18.0.10 to scm2:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy19.submitRequest over nodeId=scm2,nodeAddress=scm2/172.18.0.5:9860 after 1 failover attempts. Trying to failover after sleeping for 2000ms. com.google.protobuf.ServiceException: java.net.ConnectException: Call From 2a85192916ff/172.18.0.10 to scm3:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy19.submitRequest over nodeId=scm3,nodeAddress=scm3/172.18.0.4:9860 after 2 failover attempts. Trying to failover after sleeping for 2000ms. com.google.protobuf.ServiceException: java.net.ConnectException: Call From 2a85192916ff/172.18.0.10 to scm1:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy19.submitRequest over nodeId=scm1,nodeAddress=scm1/172.18.0.10:9860 after 3 failover attempts. Trying to failover after sleeping for 2000ms. com.google.protobuf.ServiceException: java.net.ConnectException: Call From 2a85192916ff/172.18.0.10 to scm2:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy19.submitRequest over nodeId=scm2,nodeAddress=scm2/172.18.0.5:9860 after 4 failover attempts. Trying to failover after sleeping for 2000ms. com.google.protobuf.ServiceException: java.net.ConnectException: Call From 2a85192916ff/172.18.0.10 to scm3:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy19.submitRequest over nodeId=scm3,nodeAddress=scm3/172.18.0.4:9860 after 5 failover attempts. Trying to failover after sleeping for 2000ms. com.google.protobuf.ServiceException: java.net.ConnectException: Call From 2a85192916ff/172.18.0.10 to scm1:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy19.submitRequest over nodeId=scm1,nodeAddress=scm1/172.18.0.10:9860 after 6 failover attempts. Trying to failover after sleeping for 2000ms. com.google.protobuf.ServiceException: java.net.ConnectException: Call From 2a85192916ff/172.18.0.10 to scm2:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy19.submitRequest over nodeId=scm2,nodeAddress=scm2/172.18.0.5:9860 after 7 failover attempts. Trying to failover after sleeping for 2000ms. com.google.protobuf.ServiceException: java.net.ConnectException: Call From 2a85192916ff/172.18.0.10 to scm3:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy19.submitRequest over nodeId=scm3,nodeAddress=scm3/172.18.0.4:9860 after 8 failover attempts. Trying to failover after sleeping for 2000ms. com.google.protobuf.ServiceException: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.hdds.ratis.ServerNotLeaderException): Server:3d20f0f4-1d92-455d-b069-2ba32531eaf4 is not the leader. Could not determine the leader node. at org.apache.hadoop.hdds.ratis.ServerNotLeaderException.convertToNotLeaderException(ServerNotLeaderException.java:109) at org.apache.hadoop.hdds.scm.ha.RatisUtil.checkRatisException(RatisUtil.java:246) at org.apache.hadoop.hdds.scm.protocol.StorageContainerLocationProtocolServerSideTranslatorPB.submitRequest(StorageContainerLocationProtocolServerSideTranslatorPB.java:193) at org.apache.hadoop.hdds.protocol.proto.StorageContainerLocationProtocolProtos$StorageContainerLocationProtocolService$2.callBlockingMethod(StorageContainerLocationProtocolProtos.java:62732) at org.apache.hadoop.ipc.ProtobufRpcEngine$Server.processCall(ProtobufRpcEngine.java:465) at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:578) at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:556) at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1093) at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1043) at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:971) at java.base/java.security.AccessController.doPrivileged(Native Method) at java.base/javax.security.auth.Subject.doAs(Subject.java:423) at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878) at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2976) , while invoking $Proxy19.submitRequest over nodeId=scm1,nodeAddress=scm1/172.18.0.10:9860 after 9 failover attempts. Trying to failover after sleeping for 2000ms. com.google.protobuf.ServiceException: java.net.ConnectException: Call From 2a85192916ff/172.18.0.10 to scm2:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy19.submitRequest over nodeId=scm2,nodeAddress=scm2/172.18.0.5:9860 after 10 failover attempts. Trying to failover after sleeping for 2000ms. com.google.protobuf.ServiceException: java.net.ConnectException: Call From 2a85192916ff/172.18.0.10 to scm3:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy19.submitRequest over nodeId=scm3,nodeAddress=scm3/172.18.0.4:9860 after 11 failover attempts. Trying to failover after sleeping for 2000ms. SCM is in safe mode. validated:false, DataNodeSafeModeRule, registered datanodes (=2) >= required datanodes (=3) validated:false, HealthyPipelineSafeModeRule, healthy Ratis/THREE pipelines (=0) >= healthyPipelineThresholdCount (=1) validated:true, ContainerSafeModeRule, % of containers with at least one reported replica (=1.00) >= safeModeCutoff (=0.99) validated:true, AtleastOneDatanodeReportedRule, reported Ratis/THREE pipelines with at least one datanode (=0) >= threshold (=0)
SECONDS: 119
SCM is in safe mode. validated:true, DataNodeSafeModeRule, registered datanodes (=3) >= required datanodes (=3) validated:false, HealthyPipelineSafeModeRule, healthy Ratis/THREE pipelines (=0) >= healthyPipelineThresholdCount (=1) validated:true, ContainerSafeModeRule, % of containers with at least one reported replica (=1.00) >= safeModeCutoff (=0.99) validated:true, AtleastOneDatanodeReportedRule, reported Ratis/THREE pipelines with at least one datanode (=0) >= threshold (=0)
SECONDS: 145
SCM is in safe mode. validated:true, DataNodeSafeModeRule, registered datanodes (=3) >= required datanodes (=3) validated:false, HealthyPipelineSafeModeRule, healthy Ratis/THREE pipelines (=0) >= healthyPipelineThresholdCount (=1) validated:true, ContainerSafeModeRule, % of containers with at least one reported replica (=1.00) >= safeModeCutoff (=0.99) validated:true, AtleastOneDatanodeReportedRule, reported Ratis/THREE pipelines with at least one datanode (=0) >= threshold (=0)
SECONDS: 195
SCM is out of safe mode.
Safe mode is off
Found OM leader for service omservice: om2 : LEADER (om2)
==============================================================================
Ozone-Shell-Single :: Test ozone shell CLI usage                              
==============================================================================
Test ozone shell                                                      | FAIL |
Test timeout 5 minutes exceeded.
------------------------------------------------------------------------------
Ozone-Shell-Single :: Test ozone shell CLI usage                      | FAIL |
1 test, 0 passed, 1 failed
==============================================================================
Output:  /tmp/smoketest/ozone-ha/result/robot-ozone-ha-ozone-ha-ozone-shell-single-scm1.xml
jstack 6 > /home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/ozone-ha/result/ozone-ha_datanode_1_HddsDatanodeService.stack
jstack 7 > /home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/ozone-ha/result/ozone-ha_datanode_2_HddsDatanodeService.stack
jstack 6 > /home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/ozone-ha/result/ozone-ha_datanode_3_HddsDatanodeService.stack
jstack 7 > /home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/ozone-ha/result/ozone-ha_om1_1_OzoneManagerStarter.stack
jstack 7 > /home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/ozone-ha/result/ozone-ha_om2_1_OzoneManagerStarter.stack
jstack 7 > /home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/ozone-ha/result/ozone-ha_om3_1_OzoneManagerStarter.stack
jstack 7 > /home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/ozone-ha/result/ozone-ha_recon_1_ReconServer.stack
jstack 6 > /home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/ozone-ha/result/ozone-ha_s3g_1_Gateway.stack
jstack 7 > /home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/ozone-ha/result/ozone-ha_scm1_1_StorageContainerManagerStarter.stack
jstack 7 > /home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/ozone-ha/result/ozone-ha_scm2_1_StorageContainerManagerStarter.stack
jstack 7 > /home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/ozone-ha/result/ozone-ha_scm3_1_StorageContainerManagerStarter.stack
Stopping ozone-ha_scm1_1     ... 
Stopping ozone-ha_om3_1      ... 
Stopping ozone-ha_datanode_2 ... 
Stopping ozone-ha_datanode_3 ... 
Stopping ozone-ha_datanode_1 ... 
Stopping ozone-ha_recon_1    ... 
Stopping ozone-ha_om1_1      ... 
Stopping ozone-ha_scm3_1     ... 
Stopping ozone-ha_om2_1      ... 
Stopping ozone-ha_scm2_1     ... 
Stopping ozone-ha_s3g_1      ... 
Stopping ozone-ha_s3g_1      ... done
Stopping ozone-ha_om3_1      ... done
Stopping ozone-ha_om2_1      ... done
Stopping ozone-ha_recon_1    ... done
Stopping ozone-ha_om1_1      ... done
Stopping ozone-ha_datanode_3 ... done
Stopping ozone-ha_datanode_1 ... done
Stopping ozone-ha_datanode_2 ... done
Stopping ozone-ha_scm3_1     ... done
Stopping ozone-ha_scm2_1     ... done
Stopping ozone-ha_scm1_1     ... done
Removing ozone-ha_scm1_1     ... 
Removing ozone-ha_om3_1      ... 
Removing ozone-ha_datanode_2 ... 
Removing ozone-ha_datanode_3 ... 
Removing ozone-ha_datanode_1 ... 
Removing ozone-ha_recon_1    ... 
Removing ozone-ha_om1_1      ... 
Removing ozone-ha_scm3_1     ... 
Removing ozone-ha_om2_1      ... 
Removing ozone-ha_scm2_1     ... 
Removing ozone-ha_s3g_1      ... 
Removing ozone-ha_datanode_1 ... done
Removing ozone-ha_datanode_3 ... done
Removing ozone-ha_scm1_1     ... done
Removing ozone-ha_om3_1      ... done
Removing ozone-ha_om1_1      ... done
Removing ozone-ha_datanode_2 ... done
Removing ozone-ha_recon_1    ... done
Removing ozone-ha_s3g_1      ... done
Removing ozone-ha_om2_1      ... done
Removing ozone-ha_scm3_1     ... done
Removing ozone-ha_scm2_1     ... done
Removing network ozone-ha_default
ERROR: Test execution of ozone-ha is FAILED!!!!
Output:  /home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha.xml
removed 'ozone-ha/result/robot-ozone-ha-ozone-ha-ozone-shell-single-scm1.xml'
renamed 'ozone-ha/result/dn-audit-3c12f46b672a.log' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha/dn-audit-3c12f46b672a.log'
renamed 'ozone-ha/result/dn-audit-96c327bc9acb.log' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha/dn-audit-96c327bc9acb.log'
renamed 'ozone-ha/result/dn-audit-bf838ed7326f.log' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha/dn-audit-bf838ed7326f.log'
renamed 'ozone-ha/result/docker-ozone-ha-ozone-ha-ozone-shell-single-scm1.log' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha/docker-ozone-ha-ozone-ha-ozone-shell-single-scm1.log'
renamed 'ozone-ha/result/om-audit-om1.log' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha/om-audit-om1.log'
renamed 'ozone-ha/result/om-audit-om2.log' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha/om-audit-om2.log'
renamed 'ozone-ha/result/om-audit-om3.log' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha/om-audit-om3.log'
renamed 'ozone-ha/result/ozone-ha_datanode_1_HddsDatanodeService.stack' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha/ozone-ha_datanode_1_HddsDatanodeService.stack'
renamed 'ozone-ha/result/ozone-ha_datanode_2_HddsDatanodeService.stack' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha/ozone-ha_datanode_2_HddsDatanodeService.stack'
renamed 'ozone-ha/result/ozone-ha_datanode_3_HddsDatanodeService.stack' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha/ozone-ha_datanode_3_HddsDatanodeService.stack'
renamed 'ozone-ha/result/ozone-ha_om1_1_OzoneManagerStarter.stack' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha/ozone-ha_om1_1_OzoneManagerStarter.stack'
renamed 'ozone-ha/result/ozone-ha_om2_1_OzoneManagerStarter.stack' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha/ozone-ha_om2_1_OzoneManagerStarter.stack'
renamed 'ozone-ha/result/ozone-ha_om3_1_OzoneManagerStarter.stack' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha/ozone-ha_om3_1_OzoneManagerStarter.stack'
renamed 'ozone-ha/result/ozone-ha_recon_1_ReconServer.stack' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha/ozone-ha_recon_1_ReconServer.stack'
renamed 'ozone-ha/result/ozone-ha_s3g_1_Gateway.stack' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha/ozone-ha_s3g_1_Gateway.stack'
renamed 'ozone-ha/result/ozone-ha_scm1_1_StorageContainerManagerStarter.stack' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha/ozone-ha_scm1_1_StorageContainerManagerStarter.stack'
renamed 'ozone-ha/result/ozone-ha_scm2_1_StorageContainerManagerStarter.stack' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha/ozone-ha_scm2_1_StorageContainerManagerStarter.stack'
renamed 'ozone-ha/result/ozone-ha_scm3_1_StorageContainerManagerStarter.stack' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha/ozone-ha_scm3_1_StorageContainerManagerStarter.stack'
renamed 'ozone-ha/result/s3g-audit-ad45c3b184d8.log' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha/s3g-audit-ad45c3b184d8.log'
renamed 'ozone-ha/result/scm-audit-0fdad21b9e86.log' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha/scm-audit-0fdad21b9e86.log'
renamed 'ozone-ha/result/scm-audit-2a85192916ff.log' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha/scm-audit-2a85192916ff.log'
renamed 'ozone-ha/result/scm-audit-c789eeacef1c.log' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozone-ha/scm-audit-c789eeacef1c.log'
Executing test in ozonesecure-ha
Removing network ozonesecure-ha_ozone_net
Network ozonesecure-ha_ozone_net not found.
Creating network "ozonesecure-ha_ozone_net" with the default driver
Pulling kdc (apache/ozone-testkrb5:20210419-1)...
20210419-1: Pulling from apache/ozone-testkrb5
Digest: sha256:ba7a04b9f7605b9ac64f34400f426f1e9938ad2b5be93365685097ba962ed19a
Status: Downloaded newer image for apache/ozone-testkrb5:20210419-1
Pulling kms (apache/hadoop:3)...
3: Pulling from apache/hadoop
Digest: sha256:793348d0839a55d27fb9466d4a5f7e058744866f5ab2cb7aa32f541b4810b215
Status: Downloaded newer image for apache/hadoop:3
Creating ozonesecure-ha_scm2.org_1 ... 
Creating ozonesecure-ha_om3_1      ... 
Creating ozonesecure-ha_datanode2_1 ... 
Creating ozonesecure-ha_recon_1     ... 
Creating ozonesecure-ha_scm1.org_1  ... 
Creating ozonesecure-ha_datanode3_1 ... 
Creating ozonesecure-ha_datanode1_1 ... 
Creating ozonesecure-ha_om2_1       ... 
Creating ozonesecure-ha_kdc_1       ... 
Creating ozonesecure-ha_om1_1       ... 
Creating ozonesecure-ha_kms_1       ... 
Creating ozonesecure-ha_scm3.org_1  ... 
Creating ozonesecure-ha_s3g_1       ... 
Creating ozonesecure-ha_recon_1     ... done
Creating ozonesecure-ha_datanode2_1 ... done
Creating ozonesecure-ha_scm2.org_1  ... done
Creating ozonesecure-ha_kdc_1       ... done
Creating ozonesecure-ha_om3_1       ... done
Creating ozonesecure-ha_scm1.org_1  ... done
Creating ozonesecure-ha_om1_1       ... done
Creating ozonesecure-ha_kms_1       ... done
Creating ozonesecure-ha_s3g_1       ... done
Creating ozonesecure-ha_om2_1       ... done
Creating ozonesecure-ha_datanode3_1 ... done
Creating ozonesecure-ha_scm3.org_1  ... done
Creating ozonesecure-ha_datanode1_1 ... done
ozone.scm.client.address should be set in ozone-site.xml or with the --scm option
SECONDS: 40

SECONDS: 98
com.google.protobuf.ServiceException: java.net.ConnectException: Call From scm1.org/172.25.0.116 to scm2.org:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy20.submitRequest over nodeId=scm2,nodeAddress=scm2.org/172.25.0.117:9860 after 1 failover attempts. Trying to failover after sleeping for 2000ms. com.google.protobuf.ServiceException: java.net.ConnectException: Call From scm1.org/172.25.0.116 to scm3.org:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy20.submitRequest over nodeId=scm3,nodeAddress=scm3.org/172.25.0.118:9860 after 2 failover attempts. Trying to failover after sleeping for 2000ms. com.google.protobuf.ServiceException: java.net.ConnectException: Call From scm1.org/172.25.0.116 to scm1.org:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy20.submitRequest over nodeId=scm1,nodeAddress=scm1.org/172.25.0.116:9860 after 3 failover attempts. Trying to failover after sleeping for 2000ms. com.google.protobuf.ServiceException: java.net.ConnectException: Call From scm1.org/172.25.0.116 to scm2.org:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy20.submitRequest over nodeId=scm2,nodeAddress=scm2.org/172.25.0.117:9860 after 4 failover attempts. Trying to failover after sleeping for 2000ms. com.google.protobuf.ServiceException: java.net.ConnectException: Call From scm1.org/172.25.0.116 to scm3.org:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy20.submitRequest over nodeId=scm3,nodeAddress=scm3.org/172.25.0.118:9860 after 5 failover attempts. Trying to failover after sleeping for 2000ms. com.google.protobuf.ServiceException: java.net.ConnectException: Call From scm1.org/172.25.0.116 to scm1.org:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy20.submitRequest over nodeId=scm1,nodeAddress=scm1.org/172.25.0.116:9860 after 6 failover attempts. Trying to failover after sleeping for 2000ms. com.google.protobuf.ServiceException: java.net.ConnectException: Call From scm1.org/172.25.0.116 to scm2.org:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy20.submitRequest over nodeId=scm2,nodeAddress=scm2.org/172.25.0.117:9860 after 7 failover attempts. Trying to failover after sleeping for 2000ms. com.google.protobuf.ServiceException: java.net.ConnectException: Call From scm1.org/172.25.0.116 to scm3.org:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy20.submitRequest over nodeId=scm3,nodeAddress=scm3.org/172.25.0.118:9860 after 8 failover attempts. Trying to failover after sleeping for 2000ms. com.google.protobuf.ServiceException: org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.hdds.ratis.ServerNotLeaderException): Server:da3d02cd-54a7-4b24-aeec-fee478679db0 is not the leader. Could not determine the leader node. at org.apache.hadoop.hdds.ratis.ServerNotLeaderException.convertToNotLeaderException(ServerNotLeaderException.java:109) at org.apache.hadoop.hdds.scm.ha.RatisUtil.checkRatisException(RatisUtil.java:246) at org.apache.hadoop.hdds.scm.protocol.StorageContainerLocationProtocolServerSideTranslatorPB.submitRequest(StorageContainerLocationProtocolServerSideTranslatorPB.java:193) at org.apache.hadoop.hdds.protocol.proto.StorageContainerLocationProtocolProtos$StorageContainerLocationProtocolService$2.callBlockingMethod(StorageContainerLocationProtocolProtos.java:62732) at org.apache.hadoop.ipc.ProtobufRpcEngine$Server.processCall(ProtobufRpcEngine.java:465) at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:578) at org.apache.hadoop.ipc.ProtobufRpcEngine2$Server$ProtoBufRpcInvoker.call(ProtobufRpcEngine2.java:556) at org.apache.hadoop.ipc.RPC$Server.call(RPC.java:1093) at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:1043) at org.apache.hadoop.ipc.Server$RpcCall.run(Server.java:971) at java.base/java.security.AccessController.doPrivileged(Native Method) at java.base/javax.security.auth.Subject.doAs(Subject.java:423) at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1878) at org.apache.hadoop.ipc.Server$Handler.run(Server.java:2976) , while invoking $Proxy20.submitRequest over nodeId=scm1,nodeAddress=scm1.org/172.25.0.116:9860 after 9 failover attempts. Trying to failover after sleeping for 2000ms. com.google.protobuf.ServiceException: java.net.ConnectException: Call From scm1.org/172.25.0.116 to scm2.org:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy20.submitRequest over nodeId=scm2,nodeAddress=scm2.org/172.25.0.117:9860 after 10 failover attempts. Trying to failover after sleeping for 2000ms. com.google.protobuf.ServiceException: java.net.ConnectException: Call From scm1.org/172.25.0.116 to scm3.org:9860 failed on connection exception: java.net.ConnectException: Connection refused; For more details see: http://wiki.apache.org/hadoop/ConnectionRefused, while invoking $Proxy20.submitRequest over nodeId=scm3,nodeAddress=scm3.org/172.25.0.118:9860 after 11 failover attempts. Trying to failover after sleeping for 2000ms. SCM is in safe mode. validated:false, DataNodeSafeModeRule, registered datanodes (=0) >= required datanodes (=3) validated:false, HealthyPipelineSafeModeRule, healthy Ratis/THREE pipelines (=0) >= healthyPipelineThresholdCount (=1) validated:true, ContainerSafeModeRule, % of containers with at least one reported replica (=1.00) >= safeModeCutoff (=0.99) validated:true, AtleastOneDatanodeReportedRule, reported Ratis/THREE pipelines with at least one datanode (=0) >= threshold (=0)
SECONDS: 137
SCM is in safe mode. validated:false, DataNodeSafeModeRule, registered datanodes (=0) >= required datanodes (=3) validated:false, HealthyPipelineSafeModeRule, healthy Ratis/THREE pipelines (=0) >= healthyPipelineThresholdCount (=1) validated:true, ContainerSafeModeRule, % of containers with at least one reported replica (=1.00) >= safeModeCutoff (=0.99) validated:true, AtleastOneDatanodeReportedRule, reported Ratis/THREE pipelines with at least one datanode (=0) >= threshold (=0)
SECONDS: 179
SCM is in safe mode. validated:false, DataNodeSafeModeRule, registered datanodes (=0) >= required datanodes (=3) validated:false, HealthyPipelineSafeModeRule, healthy Ratis/THREE pipelines (=0) >= healthyPipelineThresholdCount (=1) validated:true, ContainerSafeModeRule, % of containers with at least one reported replica (=1.00) >= safeModeCutoff (=0.99) validated:true, AtleastOneDatanodeReportedRule, reported Ratis/THREE pipelines with at least one datanode (=0) >= threshold (=0)
SECONDS: 214
SCM is in safe mode. validated:false, DataNodeSafeModeRule, registered datanodes (=0) >= required datanodes (=3) validated:false, HealthyPipelineSafeModeRule, healthy Ratis/THREE pipelines (=0) >= healthyPipelineThresholdCount (=1) validated:true, ContainerSafeModeRule, % of containers with at least one reported replica (=1.00) >= safeModeCutoff (=0.99) validated:true, AtleastOneDatanodeReportedRule, reported Ratis/THREE pipelines with at least one datanode (=0) >= threshold (=0)
SECONDS: 358
SCM is in safe mode. validated:false, DataNodeSafeModeRule, registered datanodes (=0) >= required datanodes (=3) validated:false, HealthyPipelineSafeModeRule, healthy Ratis/THREE pipelines (=0) >= healthyPipelineThresholdCount (=1) validated:true, ContainerSafeModeRule, % of containers with at least one reported replica (=1.00) >= safeModeCutoff (=0.99) validated:true, AtleastOneDatanodeReportedRule, reported Ratis/THREE pipelines with at least one datanode (=0) >= threshold (=0)
WARNING! Safemode is still on. Please check the docker-compose files
Stopping ozonesecure-ha_scm3.org_1  ... 
Stopping ozonesecure-ha_s3g_1       ... 
Stopping ozonesecure-ha_kms_1       ... 
Stopping ozonesecure-ha_om2_1       ... 
Stopping ozonesecure-ha_om1_1       ... 
Stopping ozonesecure-ha_kdc_1       ... 
Stopping ozonesecure-ha_datanode1_1 ... 
Stopping ozonesecure-ha_datanode3_1 ... 
Stopping ozonesecure-ha_scm1.org_1  ... 
Stopping ozonesecure-ha_recon_1     ... 
Stopping ozonesecure-ha_om3_1       ... 
Stopping ozonesecure-ha_datanode2_1 ... 
Stopping ozonesecure-ha_scm2.org_1  ... 
Stopping ozonesecure-ha_kdc_1       ... done
Stopping ozonesecure-ha_kms_1       ... done
Stopping ozonesecure-ha_om3_1       ... done
Stopping ozonesecure-ha_om2_1       ... done
Stopping ozonesecure-ha_datanode1_1 ... done
Stopping ozonesecure-ha_om1_1       ... done
Stopping ozonesecure-ha_datanode2_1 ... done
Stopping ozonesecure-ha_s3g_1       ... done
Stopping ozonesecure-ha_datanode3_1 ... done
Stopping ozonesecure-ha_recon_1     ... done
Stopping ozonesecure-ha_scm2.org_1  ... done
Stopping ozonesecure-ha_scm1.org_1  ... done
Stopping ozonesecure-ha_scm3.org_1  ... done
Removing ozonesecure-ha_scm3.org_1  ... 
Removing ozonesecure-ha_s3g_1       ... 
Removing ozonesecure-ha_kms_1       ... 
Removing ozonesecure-ha_om2_1       ... 
Removing ozonesecure-ha_om1_1       ... 
Removing ozonesecure-ha_kdc_1       ... 
Removing ozonesecure-ha_datanode1_1 ... 
Removing ozonesecure-ha_datanode3_1 ... 
Removing ozonesecure-ha_scm1.org_1  ... 
Removing ozonesecure-ha_recon_1     ... 
Removing ozonesecure-ha_om3_1       ... 
Removing ozonesecure-ha_datanode2_1 ... 
Removing ozonesecure-ha_scm2.org_1  ... 
Removing ozonesecure-ha_kdc_1       ... done
Removing ozonesecure-ha_om2_1       ... done
Removing ozonesecure-ha_datanode2_1 ... done
Removing ozonesecure-ha_s3g_1       ... done
Removing ozonesecure-ha_datanode3_1 ... done
Removing ozonesecure-ha_datanode1_1 ... done
Removing ozonesecure-ha_kms_1       ... done
Removing ozonesecure-ha_om3_1       ... done
Removing ozonesecure-ha_scm1.org_1  ... done
Removing ozonesecure-ha_om1_1       ... done
Removing ozonesecure-ha_scm2.org_1  ... done
Removing ozonesecure-ha_recon_1     ... done
Removing ozonesecure-ha_scm3.org_1  ... done
Removing network ozonesecure-ha_ozone_net
ERROR: Test execution of ozonesecure-ha is FAILED!!!!
renamed 'ozonesecure-ha/result/docker-ozonesecure-ha.log' -> '/home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/ozonesecure-ha/docker-ozonesecure-ha.log'
Exception in thread "main" java.net.SocketException: Socket closed
	at java.base/java.net.PlainSocketImpl.socketAccept(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:474)
	at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:565)
	at java.base/java.net.ServerSocket.accept(ServerSocket.java:533)
	at org.apache.hadoop.test.JacocoServer.main(JacocoServer.java:60)
Log:     /home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/log.html
Report:  /home/runner/work/ozone/ozone/hadoop-ozone/dist/target/ozone-1.3.0-SNAPSHOT/compose/result/report.html
