2022-06-24 10:39:31,010 | ERROR | S3GAudit | user=dlfknslnfslf | ip=172.18.0.9 | op=CREATE_BUCKET {bucket=[bucket-test123]} | ret=FAILURE | org.apache.hadoop.ozone.s3.exception.OS3Exception
	at org.apache.hadoop.ozone.s3.exception.S3ErrorTable.newError(S3ErrorTable.java:139)
	at org.apache.hadoop.ozone.s3.endpoint.EndpointBase.createS3Bucket(EndpointBase.java:153) 
2022-06-24 10:39:51,293 | INFO  | S3GAudit | user=tenantone$testuser | ip=172.18.0.9 | op=CREATE_BUCKET {bucket=[bucket-test1]} | ret=SUCCESS |  
2022-06-24 10:39:51,983 | INFO  | S3GAudit | user=tenantone$testuser | ip=172.18.0.9 | op=LIST_S3_BUCKETS {} | ret=SUCCESS |  
2022-06-24 10:40:12,471 | ERROR | S3GAudit | user=tenantone$testuser | ip=172.18.0.9 | op=DELETE_BUCKET {bucket=[bucket-test1]} | ret=FAILURE | org.apache.hadoop.ozone.s3.exception.OS3Exception
	at org.apache.hadoop.ozone.s3.exception.S3ErrorTable.newError(S3ErrorTable.java:139)
	at org.apache.hadoop.ozone.s3.endpoint.EndpointBase.deleteS3Bucket(EndpointBase.java:181) 
2022-06-24 10:40:13,653 | INFO  | S3GAudit | user=tenantone$testuser | ip=172.18.0.9 | op=DELETE_BUCKET {bucket=[bucket-test1]} | ret=SUCCESS |  
2022-06-24 10:40:25,448 | INFO  | S3GAudit | user=tenantone$testuser | ip=172.18.0.9 | op=CREATE_BUCKET {bucket=[bucket-test2]} | ret=SUCCESS |  
2022-06-24 10:40:26,591 | ERROR | S3GAudit | user=tenantone$testuser | ip=172.18.0.9 | op=DELETE_BUCKET {bucket=[bucket-test2]} | ret=FAILURE | org.apache.hadoop.ozone.s3.exception.OS3Exception
	at org.apache.hadoop.ozone.s3.exception.S3ErrorTable.newError(S3ErrorTable.java:139)
	at org.apache.hadoop.ozone.s3.endpoint.EndpointBase.deleteS3Bucket(EndpointBase.java:181) 
2022-06-24 10:40:27,768 | INFO  | S3GAudit | user=tenantone$testuser | ip=172.18.0.9 | op=DELETE_BUCKET {bucket=[bucket-test2]} | ret=SUCCESS |  
2022-06-24 10:40:31,993 | ERROR | S3GAudit | user=tenantone$testuser | ip=172.18.0.9 | op=CREATE_BUCKET {bucket=[bucket-test3]} | ret=FAILURE | org.apache.hadoop.ozone.s3.exception.OS3Exception
	at org.apache.hadoop.ozone.s3.exception.S3ErrorTable.newError(S3ErrorTable.java:139)
	at org.apache.hadoop.ozone.s3.endpoint.EndpointBase.createS3Bucket(EndpointBase.java:153) 
