2022-06-03 01:22:28,414 | INFO  | OMAudit | user=hadoop | ip=10.9.0.17 | op=GET_SERVICE_LIST {} | ret=SUCCESS |  
2022-06-03 01:22:40,366 | INFO  | OMAudit | user=hadoop | ip=10.9.0.17 | op=GET_SERVICE_LIST {} | ret=SUCCESS |  
2022-06-03 01:22:47,552 | INFO  | OMAudit | user=hadoop | ip=10.9.0.17 | op=GET_SERVICE_LIST {} | ret=SUCCESS |  
2022-06-03 01:22:48,102 | ERROR | OMAudit | user=hadoop | ip=10.9.0.17 | op=READ_VOLUME {volume=60748-volume-for-prepare} | ret=FAILURE | VOLUME_NOT_FOUND org.apache.hadoop.ozone.om.exceptions.OMException: Volume 60748-volume-for-prepare is not found
	at org.apache.hadoop.ozone.om.VolumeManagerImpl.getVolumeInfo(VolumeManagerImpl.java:74)
	at org.apache.hadoop.ozone.om.OzoneManager.getVolumeInfo(OzoneManager.java:2597) 
2022-06-03 01:22:56,039 | INFO  | OMAudit | user=hadoop | ip=10.9.0.17 | op=GET_SERVICE_LIST {} | ret=SUCCESS |  
2022-06-03 01:22:56,382 | INFO  | OMAudit | user=hadoop | ip=10.9.0.17 | op=LIST_VOLUMES {prevKey=, prefix=, maxKeys=1000, username=hadoop} | ret=SUCCESS |  
2022-06-03 01:22:57,142 | INFO  | OMAudit | user=hadoop | ip=10.9.0.17 | op=LIST_VOLUMES {prevKey=90353-volume-for-cancel, prefix=, maxKeys=1000, username=hadoop} | ret=SUCCESS |  
